In [74]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'john', 'mary'],
    'Age': [25, 30, 38, 40]
}

df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30
2   john   38
3   mary   40

In [53]:
lst = [['Alice', 25], ['Bob', 30], ['john', 38], ['mary', 40]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30
2   john   38
3   mary   40

In [64]:
df.head()

    Name
0  Alice
1    Bob
2   john
3   mary

In [65]:
df.tail()

    Name
0  Alice
1    Bob
2   john
3   mary

In [66]:
df.describe()

         Name
count       4
unique      4
top     Alice
freq        1

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [68]:
df['Name']

0    Alice
1      Bob
2     john
3     mary
Name: Name, dtype: str

In [75]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30
2   john   38
3   mary   40

In [70]:
df.loc[0]

Name    Alice
Name: 0, dtype: str

In [71]:
df.loc[1]

Name    Bob
Name: 1, dtype: str

In [76]:
df[df['Age'] > 25]

   Name  Age
1   Bob   30
2  john   38
3  mary   40

In [54]:
df['Gender'] = ['F','M', 'M', 'F']
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M
2   john   38      M
3   mary   40      F

In [60]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'john', 'mary'],
    'Age': [25, 30, 38, 40]
}

df = pd.DataFrame(data)

df.drop('Age', axis=1, inplace=True)

print(df)

    Name
0  Alice
1    Bob
2   john
3   mary

In [59]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False

In [57]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M
2   john   38      M
3   mary   40      F

In [58]:
df.fillna(1)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M
2   john   38      M
3   mary   40      F

In [55]:
df.groupby('Gender')['Age'].mean()

Gender
F    32.5
M    34.0
Name: Age, dtype: float64

In [80]:
import pandas as pd

df1 = pd.DataFrame({
    'key': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'john', 'mary']
})

df2 = pd.DataFrame({
    'key': [1, 2, 3, 4],
    'Age': [25, 30, 38, 40]
})

result = pd.merge(df1, df2, on='key')
print(result)

   key   Name  Age
0    1  Alice   25
1    2    Bob   30
2    3   john   38
3    4   mary   40

In [90]:


df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob']
})

df2 = pd.DataFrame({
    'Age': [25, 30]
})

df1.join(df2)

    Name  Age
0  Alice   25
1    Bob   30

In [87]:
df.sort_values('Age')

    Name  Age
0  Alice   25
1    Bob   30
2   john   38
3   mary   40

In [88]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
2    39
3    41
Name: Age, dtype: int64

In [89]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'john', 'mary']
Length: 4, dtype: str

In [91]:
df['Age'].value_counts()

Age
25    1
30    1
38    1
40    1
Name: count, dtype: int64